### ISSUE TITLE
parse_bracken_output.py produces DOS format output files

### ISSUE THREAD

**Issue by DiDigsDNA** [BCCDC-PHL/dehost-and-verify-illumina#13]
These output files are incompatible with Linux paste command in combine_pre_and_post_dehosting.nf

https://github.com/BCCDC-PHL/dehost-and-verify-illumina/blob/01f411b1f3b40069ee03e0528f56027adf022c34/modules/combine_pre_and_post_dehosting.nf#L13

Output standard unix tsv files please :)

**Comment by dfornika** [comment]
Note to self: this page explains how to create a custom 'dialect' for the python `csv` module:

https://pymotw.com/2/csv/#creating-a-dialect

**Comment by DiDigsDNA** [comment]
That's great info to have, thanks.
