### ISSUE TITLE
Re-generate test input, using only chr22 instead of full human genome

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/dehost-and-verify-illumina#6]
Our initial set of test input was created by simulating reads from the full hg38 human genome.

Due to the 5Gb cache size limit on the 'GitHub Actions' CI testing workflow, we need to use a smaller reference genome.

We will use just chr22 from hg38 instead of the full human genome as a reference. Available here:

ftp://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz

**Comment by DiDigsDNA** [comment]
Complete, pull request issued!
